name: Publish package

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
    inputs:
      EXTENSION_TAG:
        description: "branch/tag of the extension to build."
        type: string
        default: main
jobs:
  should-build-change:
    runs-on: ubuntu-latest
    outputs:
      repo-cache-hit: ${{ steps.cache-last-commit.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          git rev-parse HEAD >> ./HEAD
      - name: Check New Changes
        id: cache-last-commit
        uses: actions/cache@v4
        with:
          path: HEAD
          key: HEAD-${{ hashFiles('HEAD') }}

  release-job:
    runs-on: ubuntu-latest
    needs: should-build-change
    if: ${{ needs.should-build-change.outputs.repo-cache-hit != 'true' || github.event_name != 'schedule' }}
    steps:
      - name: Checkout Extension
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.EXTENSION_TAG }}

      - name: Set Up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Check Out Continue as Git Submodule
        run: git submodule update --init --recursive

      - name: Install Dependencies
        run: npm run install-dependencies

      - name: Build Extension
        run: npm run build

      - name: Create Packages
        run: |
          npm run create-darwin-arm64-package
          npm run create-linux-x64-package
          npm run create-linux-arm64-package
          npm run create-win32-x64-package

      - name: Publish Packages to VS Code Marketplace
        run: |
          npx @vscode/vsce publish -p ${{ secrets.VSCODE_MARKETPLACE_TOKEN }} --pre-release -i build/*darwin-arm64*.vsix
          npx @vscode/vsce publish -p ${{ secrets.VSCODE_MARKETPLACE_TOKEN }} --pre-release -i build/*linux-x64*.vsix
          npx @vscode/vsce publish -p ${{ secrets.VSCODE_MARKETPLACE_TOKEN }} --pre-release -i build/*linux-arm64*.vsix
          npx @vscode/vsce publish -p ${{ secrets.VSCODE_MARKETPLACE_TOKEN }} --pre-release -i build/*win32-x64*.vsix
